USE [master]
GO

/****** Object:  Database [CONSOLIDADO_KARDEX]    Script Date: 1/13/2026 11:38:42 AM ******/
CREATE DATABASE [CONSOLIDADO_KARDEX]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CONSOLIDADO_KARDEX', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CONSOLIDADO_KARDEX.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CONSOLIDADO_KARDEX_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CONSOLIDADO_KARDEX_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CONSOLIDADO_KARDEX].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET ARITHABORT OFF 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET  MULTI_USER 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CONSOLIDADO_KARDEX] SET  READ_WRITE 
GO


