USE [CONSOLIDADO_KARDEX]
GO

/****** Object:  StoredProcedure [dbo].[SP_PrecioTiendasCompras_FR]    Script Date: 1/13/2026 11:22:32 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE OR ALTER PROCEDURE [dbo].[SP_PrecioTiendasCompras_FR]
-- =============================================
-- Author:		Adrian Rodriguez
-- Create date: 2026-01-13
-- Description:	Consolidado Kardex Peru
-- =============================================
AS
BEGIN
	SET NOCOUNT ON;
	SET XACT_ABORT ON;
	BEGIN TRY
		BEGIN TRANSACTION

			DECLARE @FechaHoy DATE = CAST(GETDATE() AS DATE)
			DECLARE @FilasInsertadas INT;
			DECLARE @FilasEliminadas INT;

			TRUNCATE TABLE CONSOLIDADO_KARDEX.dbo.PreciosTiendasCompras;

			SELECT @FilasEliminadas = @@ROWCOUNT;

			INSERT INTO CONSOLIDADO_KARDEX.dbo.PreciosTiendasCompras (Sucursal, Referencia, CostProm, Fecha)
			SELECT 'JOCKEY' AS Sucursal, REFERENCIA, AVG(CostProm), CAST(FECHAALBARAN AS DATE) AS Fecha
			FROM [172.16.17.250].[PERU_Frontrest].dbo.vw_Jockey_PrecioCompras
			WHERE CAST(FECHAALBARAN AS DATE) = @FechaHoy
			GROUP BY REFERENCIA, FECHAALBARAN

			UNION ALL
			SELECT 'SJL' AS Sucursal, REFERENCIA, AVG(CostProm), CAST(FECHAALBARAN AS DATE)
			FROM [172.16.17.250].[PERU_Frontrest].dbo.vw_SJL_PrecioCompras
			WHERE CAST(FECHAALBARAN AS DATE) = @FechaHoy
			GROUP BY REFERENCIA, FECHAALBARAN


			UNION ALL
			SELECT 'PARDO' AS Sucursal, REFERENCIA, AVG(CostProm), CAST(FECHAALBARAN AS DATE)
			FROM [172.16.17.250].[PERU_Frontrest].dbo.vw_PARDO_PrecioCompras
						WHERE CAST(FECHAALBARAN AS DATE) = @FechaHoy

			GROUP BY REFERENCIA, FECHAALBARAN

			UNION ALL
			SELECT 'ROSEDAL' AS Sucursal , REFERENCIA, AVG(CostProm), CAST(FECHAALBARAN AS DATE)
			FROM [172.16.17.250].[PERU_Frontrest].dbo.vw_ROSEDAL_PrecioCompras
			GROUP BY REFERENCIA, FECHAALBARAN

			UNION ALL
			SELECT 'PURUCHUCO' AS Sucursal, REFERENCIA, AVG(CostProm), CAST(FECHAALBARAN AS DATE)
			FROM [172.16.17.250].[PERU_Frontrest].dbo.vw_PURUCHUCO_PrecioCompras
			GROUP BY REFERENCIA, FECHAALBARAN

			UNION ALL
			SELECT 'CANADA' AS Sucursal, REFERENCIA, AVG(CostProm), CAST(FECHAALBARAN AS DATE)
			FROM [172.16.17.250].[PERU_Frontrest].dbo.vw_CANADA_PrecioCompras
			GROUP BY REFERENCIA, FECHAALBARAN

			UNION ALL
			SELECT 'PYA' AS Sucursal , REFERENCIA, AVG(CostProm), CAST(FECHAALBARAN AS DATE)
			FROM [172.16.17.250].[PERU_Frontrest].dbo.vw_PYA_PrecioCompras
			GROUP BY REFERENCIA, FECHAALBARAN

			UNION ALL
			SELECT 'CHILCLAYO' AS Sucursal, REFERENCIA, AVG(CostProm), CAST(FECHAALBARAN AS DATE)
			FROM [172.16.17.250].[PERU_Frontrest].dbo.vw_CHILCLAYO_PrecioCompras
			GROUP BY REFERENCIA, FECHAALBARAN

			UNION ALL
			SELECT 'MDS' AS Sucursal, REFERENCIA, AVG(CostProm), CAST(FECHAALBARAN AS DATE)
			FROM [172.16.17.250].[PERU_Frontrest].dbo.vw_MDS_PrecioCompras
			GROUP BY REFERENCIA, FECHAALBARAN

			UNION ALL
			SELECT 'CC' AS Sucursal, REFERENCIA, AVG(CostProm), CAST(FECHAALBARAN AS DATE)
			FROM [172.16.17.250].[PERU_Frontrest].dbo.vw_CCIVICO_PrecioCompras
			GROUP BY REFERENCIA, FECHAALBARAN

			UNION ALL
			SELECT 'SALAVERRY' AS Sucursal, REFERENCIA, AVG(CostProm), CAST(FECHAALBARAN AS DATE)
			FROM [172.16.17.250].[PERU_Frontrest].dbo.vw_SALAVERRY_PrecioCompras
			GROUP BY REFERENCIA, FECHAALBARAN

			UNION ALL
			SELECT 'FONTANA' AS Sucursal , REFERENCIA, AVG(CostProm), CAST(FECHAALBARAN AS DATE)
			FROM [172.16.17.250].[PERU_Frontrest].dbo.vw_FONTANA_PrecioCompras
			GROUP BY REFERENCIA, FECHAALBARAN

			UNION ALL
			SELECT 'AREQUIPA' AS Sucursal, REFERENCIA, AVG(CostProm), CAST(FECHAALBARAN AS DATE)
			FROM [172.16.17.250].[PERU_Frontrest].dbo.vw_AREQUIPA_PrecioCompras
			GROUP BY REFERENCIA, FECHAALBARAN

			UNION ALL
			SELECT 'MINKA' AS Sucursal, REFERENCIA, AVG(CostProm), CAST(FECHAALBARAN AS DATE)
			FROM [172.16.17.250].[PERU_Frontrest].dbo.vw_MINKA_PrecioCompras
			GROUP BY REFERENCIA, FECHAALBARAN

			SET @FilasInsertadas = @@ROWCOUNT;
			PRINT ' ------> Filas Insertadas: ' + CAST(@FilasInsertadas - @FilasEliminadas AS VARCHAR(20));
		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
	    ROLLBACK TRANSACTION
        DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
        RAISERROR(@ErrorMessage, 16, 1);
    END CATCH
END
GO


